version: "3"

services:

  ftpd: 
    image: "stilliard/pure-ftpd:latest"
    container_name: ftpd
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ../../_custom/env.conf
    ports:
      - "21:21"
      - "30000-30020:30000-30020"
    volumes:
      - ../../_custom/ftp-data:/home/ftpdata



  ftpd-www:
    image: nginx:latest
    container_name: ftpd-www
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_custom/env.conf
    ports:
      - "2180:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ../../_custom/ftp-data:/resources
