version: "3"

services:

  etracs-server:
    container_name: etracs-server
    image: ramesesinc/etracs-server-city:beta
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports:
      - "8060:8060"
      - "8061:8061"
      - "8070:8070"
    volumes:
      - ./templates:/apps/server/templates
      - ./plugin-services/rpt-obo-services.jar:/apps/etracs25/modules/rpt-obo-services.jar
      - ./server-updates/rameses-enterprise-admin-services.jar:/apps/server/services/modules/admin/rameses-enterprise-admin-services.jar
      - ./server-updates/rameses-gov-etracs-rptis-online-services.jar:/apps/server/services/modules/rptis/rameses-gov-etracs-rptis-online-services.jar
      - ./server-updates/rameses-gov-etracs-rptis-city-services.jar:/apps/server/services/modules/rptis/rameses-gov-etracs-rptis-city-services.jar
      - ./server-updates/rameses-gov-treasury-services.jar:/apps/server/services/modules/treasury/rameses-gov-treasury-services.jar
      - ./server-updates/rameses-treasury-common-services.jar:/apps/server/services/modules/treasury/rameses-treasury-common-services.jar

      - ../../_custom/output:/apps/server/output
      - ../../_custom/datasources:/services/datasources
      - ../../_res/connections:/apps/etracs25/connections/ext
      - ../../_custom/module-server:/apps/etracs25/modules/ext/zzz-lgu-custom-module

