version: "3"

services:

  boracay-server:
    image: "ramesesinc/enterprise-common-server:255.04.001"
    container_name: boracay-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ../../_custom/env.conf
    ports:
      - "8096:8070"
    volumes:
      - ../../_res/connections:/apps/server/services/apps/enterprise/connections/ext
      - ../../_custom/datasources/boracayds:/apps/server/services/datasources/mainds
      - ../../_custom/module-client/obo:/apps/server/templates/custom
      - ../../_custom/output:/apps/server/output
      - ./module-client/reports:/apps/server/templates 
      - ./server-modules:/enterprise/modules